name: "Auto Add Assign"

on:
  pull_request:

permissions: write-all

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Assign
        if: github.event.pull_request.assignee == null
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.event.pull_request.user.login }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
